#!/usr/bin/env bash
#installs nginx server

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-get install haproxy=2.6.\*
sudo apt-get update
sudo apt-get install haproxy
sudo sed -i -e '$aEnabled=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 226884-web-01 107.23.91.47 check\n\tserver 226884-web-02 35.174.211.188 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
