#!/usr/bin/env bash
#installs nginx server

sudo service haproxy stop
sudo apt-get purge -y haproxy

sudo apt update
sudo apt install -y haproxy

sudo sed -i '$aENABLED=1' /etc/default/haproxy

sudo sed -i '$a\\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 226884-web-01 107.23.91.47:80 check\n\tserver 226884-web-02 35.174.211.188:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
