#!/usr/bin/env bash
# Add custom header to nginx configuration to return hostname

sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html /var/www/error
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/404.html

server_config=\
"server {
        listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
	           try_files $uri $uri/ =404;
	}
	location /redirect_me {
        	return 301 http://github.com/;
	}
        error_page 404 /404.html;
	location = /404.html {
	        internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
	        
